### ISSUE TITLE
Issue: Pokemon Moves

### ISSUE THREAD

**Issue by CodiWanKenobi** [tmcdaniel511/EE461L-Team-Project#21]
As a competitive Pokémon player/casual Pokémon gamer I would like to see all of the moves that Pokémon can learn so that I know the effects, type, and stats of each move when I am confronted with an unfamiliar move in battle.

**Comment by CodiWanKenobi** [comment]
Added!
![Screenshot_158](https://user-images.githubusercontent.com/32813747/76135629-5029e700-5fee-11ea-8e5f-edb3fc20cdc4.png)

**Comment by JaimeTan** [comment]
Added all moves from database! [Estimate: Phase II; Completed: Phase II (3 hours)]
![image](https://user-images.githubusercontent.com/32779789/78090878-00da9a80-7391-11ea-8f6a-b96838e63010.png)
