### ISSUE TITLE
Issue: Pokemon Ability

### ISSUE THREAD

**Issue by CodiWanKenobi** [tmcdaniel511/EE461L-Team-Project#25]
As a casual Pokémon gamer, I would like to learn more about the different abilities that Pokémon can possess so I know what I am up against when I face the Pokémon Gym Leaders as well as the Elite Four and Champion.

**Comment by CodiWanKenobi** [comment]
![Screenshot_162](https://user-images.githubusercontent.com/32813747/76135720-5ff5fb00-5fef-11ea-97c8-d344d83df8a7.png)

**Comment by JaimeTan** [comment]
Completed with all fetched items. Completed: Phase II (4 hours)
![image](https://user-images.githubusercontent.com/32779789/78090691-72661900-7390-11ea-9fc7-259811dcb489.png)
