### ISSUE TITLE
Issue: Pokemon Team Builder

### ISSUE THREAD

**Issue by CodiWanKenobi** [tmcdaniel511/EE461L-Team-Project#26]
As a Pokémon enthusiast, I would like to create my very own team to see how compatible they would be instead of wasting time in the game collecting them.

**Comment by CodiWanKenobi** [comment]
Added a rough skeleton
![Screenshot_163](https://user-images.githubusercontent.com/32813747/76135747-a21f3c80-5fef-11ea-8314-76f492e1f0d8.png)

**Comment by JaimeTan** [comment]
![image](https://user-images.githubusercontent.com/32779789/78090483-dfc57a00-738f-11ea-9347-96736daa4c4c.png)

You can add Pokemon to the team.
